# Generated by Django 2.2.2 on 2019-07-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_weddingname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weddingName',
        ),
    ]
